# Generated by Django 6.0.3 on 2026-04-14 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PredictionUsersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('maritalStatus', models.CharField(blank=True, max_length=30, null=True)),
                ('numberOfDependents', models.PositiveIntegerField(default=0)),
                ('educationLevel', models.CharField(blank=True, max_length=50, null=True)),
                ('yearsAtCompany', models.PositiveIntegerField(default=0)),
                ('monthlyIncome', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jobLevel', models.CharField(blank=True, max_length=30, null=True)),
                ('jobRole', models.CharField(blank=True, max_length=100, null=True)),
                ('companySize', models.CharField(blank=True, max_length=20, null=True)),
                ('companyTenure', models.PositiveIntegerField(blank=True, null=True)),
                ('numberOfPromotions', models.PositiveIntegerField(default=0)),
                ('overtime', models.BooleanField(default=False)),
                ('remoteWork', models.BooleanField(default=False)),
                ('distanceFromHome', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
