# Generated by Django 6.0.3 on 2026-04-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_hire_date_predictionusersprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='candidate_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hire_date',
        ),
        migrations.DeleteModel(
            name='PredictionUsersProfile',
        ),
    ]
