# Generated by Django 6.0.3 on 2026-04-15 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=1)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('benchmark_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('max_days_per_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=30)),
                ('number_of_dependents', models.PositiveIntegerField(default=0)),
                ('has_disability', models.BooleanField(default=False)),
                ('Location', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('employment_type', models.CharField(max_length=50)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('years_at_company', models.PositiveIntegerField(default=0)),
                ('number_of_promotions', models.PositiveIntegerField(default=0)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('default_clock_in', models.TimeField(blank=True, null=True)),
                ('default_clock_out', models.TimeField(blank=True, null=True)),
                ('contracted_hours', models.PositiveIntegerField(default=40)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management.job')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_days', models.PositiveIntegerField(default=0)),
                ('remaining_days', models.PositiveIntegerField(default=0)),
                ('max_days_per_year', models.PositiveIntegerField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('employee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_entitlements', to='employee_management.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_management.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='employee_management.department')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_management.team'),
        ),
    ]
