# Generated by Django 6.0.3 on 2026-04-09 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Full job description text')),
                ('required_skills', models.JSONField(default=list)),
                ('min_experience_years', models.FloatField(default=0)),
                ('required_degree', models.CharField(default='Unknown', max_length=20)),
                ('weight_skills', models.FloatField(default=0.4)),
                ('weight_experience', models.FloatField(default=0.3)),
                ('weight_education', models.FloatField(default=0.1)),
                ('weight_semantic', models.FloatField(default=0.2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(blank=True, max_length=255)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('candidate_skills', models.JSONField(default=list)),
                ('candidate_degree', models.CharField(default='Unknown', max_length=20)),
                ('candidate_years_exp', models.FloatField(default=0.0)),
                ('exp_extraction_method', models.CharField(blank=True, max_length=50)),
                ('skills_score', models.FloatField(null=True)),
                ('experience_score', models.FloatField(null=True)),
                ('education_score', models.FloatField(null=True)),
                ('semantic_score', models.FloatField(null=True)),
                ('ats_score', models.FloatField(null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applying', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='resume_pipeline.job')),
            ],
            options={
                'ordering': ['-ats_score'],
            },
        ),
    ]
