# Generated by Django 6.0.3 on 2026-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='error_message',
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('shortlisted', 'Shortlisted'), ('in-progress', 'In-Progress'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
